name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write
  statuses: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true

      - name: Close PR if commits are not conventional
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "This PR is being closed because it does not follow the Conventional Commits guidelines. Please update your commit messages and reopen the PR."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
