name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        id: verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true

      - name: Close PR if commits are not conventional
        if: steps.verify.outputs.semantic == 'false'
        run: |
          gh pr close ${{ github.event.pull_request.number }} --comment "This PR is being closed because it does not follow the Conventional Commits guidelines. Please update your commit messages and reopen the PR."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send email notification
        if: steps.verify.outputs.semantic == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "PR #${{ github.event.pull_request.number }} Closed"
          body: "The PR #${{ github.event.pull_request.number }} was closed because it does not follow the Conventional Commits guidelines."
          to: ${{ github.event.pull_request.user.email }}
          from: carolina.greenholt@ethereal.email