name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 12 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install pytest  # Install pytest

      - name: Run tests with pytest
        run: |
          pytest  # Run pytest to test the code

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo:nightly .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo:nightly

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: failure()  # Only run if the build-and-test job fails

    steps:
      - name: Send notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.ethereal.email
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Nightly Build Failed"
          body: "Nightly build failed! Please check the logs."
          to: ${{ secrets.EMAIL_TO }}
          bcc: ${{ secrets.EMAIL_BCC }}
          from: carolina.greenholt@ethereal.email
